name: docker image building and pushing

on:
  push:
    branches:
      - 'aarch64'
  pull_request:
    branches: [ infer-aarch64 ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Will build everyday at 4:30 and 16:30
    - cron:  '30 4,16 * * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:  
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push infer
        uses: docker/build-push-action@v3
        with:
          context: ssh-agent/.
          platforms: linux/arm64
          push: true
          tags: gounthar/jenkinsci-docker-android-base:infer-aarch64
